### PR TITLE
Pull Request for Login Screen Music Feature and Controls for Audio tag

### PR DESCRIPTION
**Pull request by asetiadi001**
Hi,

I have made 2 main feature in my fork, namely:

- Login Screen Music

- Controls LocalPlayer (increase decrease music sound)

I hope you can accept my proposition :)

### CODE REVIEW

**Comment by jareddr** [comment]
Thanks man!

I haven't been able to bring myself to work on this since I first launched it, but I really appreciate your attention on it.

I'll try to check out your changes tonight and will undoubtedly accept your pull request once I've looked.

**Comment by jareddr** [comment]
Oh also, have you tested this with maps at all?  I'm pretty sure the worldAreas.json file is no longer correct for maps since Atlas of Worlds.

All of the world area names need to be updated.

**Comment by asetiadi001** [comment]
I haven't tested this with maps yet, will do Once I reach merciless LoL.

**Comment by jareddr** [comment]
A year later and I finally updated the project!  I didn't merge your pull request but I did implement the features you suggested, thanks again!

**Pull request closed without merging**
